package carrentalsystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author merve çelik
 */
public class Log extends javax.swing.JFrame {
Connection con = null;
Statement st=null;      //initialize the  vars
ResultSet rs =null;

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //gets the default toolkit which i set design 
         //and  then get screen size which i set  before
        //and generate the dimension  //also set undecorated
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //set frame location like that becuase in the middle of the screen
        this.setBackground(new Color(0, 0, 0, 0)); //set  frame background like  that for be not opaque
        jPanel2.setBackground(new Color(0, 0, 0, 0));  //set  panel background like  that for be not opaque
        txtname.setBackground(new Color(0, 0, 0, 0)); //set  txtbackground like  that for be not opaque
        txtpass.setBackground(new Color(0, 0, 0, 0)); //set  txtbackground like  that for be not opaque
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblpass = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel2.setText("Car Rental System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 55, 330, -1));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblname.setText("Username");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(102, 102, 102));
        txtname.setText("Enter your name");
        txtname.setBorder(null);
        txtname.setOpaque(false);
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 266, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 179, 308, -1));

        lblpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblpass.setText("Password");
        jPanel2.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        txtpass.setBorder(null);
        txtpass.setOpaque(false);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 300, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 300, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Admin Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 280, 110, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("User Login");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\merve çelik\\Desktop\\382168.jpg")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 860, 480));

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       this.dispose(); //frame disappear
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
      txtname.setText(""); ////  this method invoked when a component gains the keyboard focus  and set text as if any string  in it all of 
       //them is gone
    }//GEN-LAST:event_txtnameFocusGained

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
      txtpass.setText("");//  this method invoked when a component gains the keyboard focus  and set text as if any string  in it all of 
       //them is gone
    }//GEN-LAST:event_txtpassFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(txtname.getText().isEmpty()||txtpass.getText().isEmpty()){
           //if textfield or password field is empty show the message
           JOptionPane.showMessageDialog(this, "Enter the username  and password ..");  
          txtname.setText("");      //and then reset fields
          txtpass.setText("");
       }else {
           
        PreparedStatement ps; //for paramaterited query
       ResultSet rs;
       String username=txtname.getText();      //hold text fields info as a string
       String pass=txtpass.getText();
       String query="SELECT * FROM LOG WHERE USERNAME=? AND PASSWORD=?"; //
    try {
        ps =javaconnect.getConnection().prepareStatement(query); 
       ps.setString(1, username); 
       ps.setString(2, pass); 
        rs=ps.executeQuery(); //execute givrn query
        if(rs.next()){ //when in specific  name in database 
           new Userlog().setVisible(true); //shows userlog frame
           this.dispose();
          new Userlog().setLocationRelativeTo(null); //shows userlog frame in the middle of screen
         
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please check your username and password"); //if not in db show this message
        }
    } catch (SQLException ex) {
        Logger.getLogger(Log.class.getName()).log(Level.SEVERE, null, ex);
    }
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(txtname.getText().isEmpty()||txtpass.getText().isEmpty()){
           //if textfield or password field is empty show the message
           JOptionPane.showMessageDialog(this, "Enter the username  and password ..");  
          txtname.setText("");      //and then reset fields
          txtpass.setText("");
       }else {
           
    CarManager manager=new CarManager();    //create a car manager  object
         
          if(txtname.getText().equals("Merve")&&txtpass.getText().equals("12345@aD")){
               //if username text is equalivent to "Ada Nil so on also when i checked regex password  and equals true password 
             RegexPasswordControl reg=new RegexPasswordControl();
             //for the controls create regex object
             
              if (reg.validate(txtpass.getText())==true){
                this.dispose();
                manager.setVisible(true);
                
                //shows  car manager frame and  also set frame  location in the middle of the screen
                
               manager.setLocationRelativeTo(null); 
               
              
              }else{
                 JOptionPane.showMessageDialog(this, "Your password cannot  be include @ or lower and uppercase letter also not correct ");
             //shows the messsage
              }
               
          }else if(!txtname.getText().equals("Merve")){  //if username text is not  equals Merve
            JOptionPane.showMessageDialog(this,"You used to login wrong side Please use User login");  //shows the messsage
           manager.setVisible(false);  //do not show  car manager frame(admin frame) 
          }

       
          else {
               JOptionPane.showMessageDialog(this, "Wrong  username or password  ");  //shows the messsage
         }
        
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
